- name: Install HA proxy
  apt:
    name: haproxy
    state: present
    update_cache: yes
  notify: restart haproxy

- name: Add HA proxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Enable and start HA proxy service
  service:
    name: haproxy
    state: started
    enabled: yes
