- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: restart nginx

- name: Add nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Enable and start nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Stop nginx service
  service: 
    name: nginx 
    state: stopped
