- name: Show Ansible configuration file
  debug:
    var: ansible_config

- hosts: webservers
  become: yes
  roles:
    - nginx

- hosts: loadbalancers
  become: yes
  roles:
    - ha-proxy
    - keepalived
