- name: Install keepalived 
  apt:
    name: keepalived 
    state: present 
    update_cache: yes 
  notify: restart keepalived

- name: Add keepalived config 
  template:
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf 
  notify : restart keepalived 

- name : Enable and start keepalived service 
  service:
    name : keepalived 
    enabled : yes 
    state : started 
